name: WordPress Plugin Check

on:
  push:
    branches: [main]
    paths:
      - '**.php'
      - 'assets/**'
      - 'readme.txt'
  pull_request:
    branches: [main]
    paths:
      - '**.php'
      - 'assets/**'
      - 'readme.txt'

permissions:
  contents: read

jobs:
  plugin-check:
    name: Plugin Check
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: wordpress/plugin-check-action@98a1788320d0add90df2d8183934ecccbc4e05d2 # v1.1.7
